[network]
rpc_url = "https://api.mainnet-beta.solana.com"
websocket_url = "wss://api.mainnet-beta.solana.com"
commitment = "confirmed"
auto_discover_validators = true
max_validator_connections = 5

[storage]
database_url = "sqlite:sni.db"
enable_compression = true
batch_size = 1000
flush_interval_ms = 5000

[api]
host = "0.0.0.0"
port = 8080
enable_graphql = true
enable_websockets = true
cors_origins = ["*"]

[indexing]
index_accounts = true
index_transactions = true
index_blocks = true
track_validators = true
track_network_health = true
program_filters = []